name: Ghidra NSIS Extension Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghidra:
          - "11.1.2"
          - "11.1.1"
          - "11.1"
          - "11.0.3"
          - "11.0.2"
          - "11.0.1"
          - "11.0"

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Ghidra ${{ matrix.ghidra }}
      uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}

    - name: Build
      run: cd nsis; gradle buildExtension

    - name: Upload built extension
      uses: actions/upload-artifact@v4
      with:
        name: NSIS_Ghidra_${{ matrix.ghidra }}
        path: nsis/dist/*.zip

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: build

    steps:
    - name: Download built extension
      uses: actions/download-artifact@v4

    - name: Upload extension to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.zip'
